spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: eureka-client-user

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
user:
  name: Felix
  role: Employee

github:
  PersonalAccessToken: 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
